dist: xenial

language: python
python:
  - "3.8"

notifications:
  email:
    - powen@renci.org

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PATH=$PWD/bin:$PATH
    - PYTHONPATH=$PWD/QRW

# command to run tests
script:
  - pytest -p no:warnings QRW/unittests
#  - qrw test

after_success:
  - coveralls