openapi: 3.0.2
info:
  title: Question Rewrite (placeholder) - A Swagger UI/web service
  description: 'A Swagger UI/web service interface (placeholder) for the Question Rewrite service'
  version: '0.0.1'
  contact:
    email: whomever@renci.org
  termsOfService: http://robokop.renci.org:7055/tos?service_long=Question+rewrite+service&provider_long=the+Translator+Consortium
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: QRW
paths:
  /get:
    get:
      tags:
        - QRW
      summary: 'Get questions related to a question. question validated against Translator Interchange format'
      description: ''
      parameters:
        - in: query
          name: query
          schema:
            type: json
            example:
              -  '{}'
      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: json
                example:
                  request: response