openapi: 3.0.2
info:
  title: Question Augmentation - A Swagger UI/web service
  description: 'Question Augmentation accepts ReasonerAPI Std (0.9.2) messages that must contain a query_graph.  It
  returns a list of augmented query graphs.
  <p/>
  <b>node_expand</b> creates new questions by adding nodes similar to original nodes.  In this prototype, it only applies
  to chemical_substance nodes.
  <b>edge_expand</b> creates new questions by replacing individual predicates with related predicates or pairs of predicates.
  This potentially turns e.g. one-hop questions into two-hop questions.
'
  version: '0.0.1'
  contact:
    email: whomever@renci.org
  termsOfService: http://robokop.renci.org:7055/tos?service_long=Question+augmentation+service&provider_long=the+Translator+Consortium
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Interfaces
paths:
  /node_expand:
    post:
      tags:
        - Interfaces
      summary: 'Creates new questions by expanding certain node types into pairs or groups of similar node types'
      description: ''
      requestBody:
        content:
          application/json:
              schema:
                "$ref": "#/definitions/Request"
        description: A question graph
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/definitions/Request"
          description: 'Example: Returns an array of expanded nodes and edges'

  /edge_expand:
    post:
      tags:
        - Interfaces
      summary: 'Creates a list of new questions by replacing individual edges with related edges or groups of edges.'
      description: ''
      parameters:
        - in: query
          name: depth
          required: true
          default: 1
          example: 1
      requestBody:
        content:
          application/json:
              schema:
                "$ref": "#/definitions/Request"
        description: A question graph
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/definitions/Request"
          description: 'Example: Returns an array of expanded edges and nodes'

definitions:
  Request:
    type: object
    title: The Request Schema
    description: A Question Augmentation request.
    properties:
      message:
        "$id": "#/properties/message"
        type: object
        title: The Message Schema
        description: An explanation about the purpose of this instance.
        default: {}
        example:
          query_graph:
            nodes:
            - id: node_0
              type: chemical_substance
            - type: disease
              id: node_1
            edges:
            - id: edge_0
              source_id: node_0
              type: treats
              target_id: node_1
        required:
        - query_graph
        properties:
          query_graph:
            "$id": "#/properties/message/properties/query_graph"
            type: object
            title: The Query_graph Schema
            description: An explanation about the purpose of this instance.
            default: {}
            example:
              edges:
              - target_id: node_1
                id: edge_0
                source_id: node_0
                type: treats
              nodes:
              - id: node_0
                type: chemical_substance
              - id: node_1
                type: disease
            required:
            - nodes
            - edges
            properties:
              nodes:
                "$id": "#/properties/message/properties/query_graph/properties/nodes"
                type: array
                title: The Nodes Schema
                description: An explanation about the purpose of this instance.
                default: []
                items:
                  "$id": "#/properties/message/properties/query_graph/properties/nodes/items"
                  type: object
                  title: The Items Schema
                  description: An explanation about the purpose of this instance.
                  default: {}
                  example:
                  - id: node_0
                    type: chemical_substance
                  - id: node_1
                    type: disease
                  required:
                  - id
                  - type
                  properties:
                    id:
                      "$id": "#/properties/message/properties/query_graph/properties/nodes/items/properties/id"
                      type: string
                      title: The Id Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - node_0
                    type:
                      "$id": "#/properties/message/properties/query_graph/properties/nodes/items/properties/type"
                      type: string
                      title: The Type Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - chemical_substance
              edges:
                "$id": "#/properties/message/properties/query_graph/properties/edges"
                type: array
                title: The Edges Schema
                description: An explanation about the purpose of this instance.
                default: []
                items:
                  "$id": "#/properties/message/properties/query_graph/properties/edges/items"
                  type: object
                  title: The Items Schema
                  description: An explanation about the purpose of this instance.
                  default: {}
                  example:
                  - target_id: node_1
                    id: edge_0
                    source_id: node_0
                    type: treats
                  required:
                  - id
                  - type
                  - source_id
                  - target_id
                  properties:
                    id:
                      "$id": "#/properties/message/properties/query_graph/properties/edges/items/properties/id"
                      type: string
                      title: The Id Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - edge_0
                    type:
                      "$id": "#/properties/message/properties/query_graph/properties/edges/items/properties/type"
                      type: string
                      title: The Type Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - treats
                    source_id:
                      "$id": "#/properties/message/properties/query_graph/properties/edges/items/properties/source_id"
                      type: string
                      title: The Source_id Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - node_0
                    target_id:
                      "$id": "#/properties/message/properties/query_graph/properties/edges/items/properties/target_id"
                      type: string
                      title: The Target_id Schema
                      description: An explanation about the purpose of this instance.
                      default: ''
                      example:
                      - node_1
