apiVersion: v1
items:

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: qrw-web-data-pv-volume
  spec:
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: 5Gi
    hostPath:
      path: "/c/Users/powen/PycharmProjects/qrw-web-data"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: qrw-web-data-pv

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: qrw-web-data-pvc
    labels:
      type: local
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: qrw-web-data-pv
kind: List
