apiVersion: v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: qrw-web-dep
    labels:
      service: qrw-web-service
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: qrw-web-service
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: qrw-web-service
      spec:
        containers:
        - name: qrw-web
          image: renciorg/qrw
          ports:
            - containerPort: 6380
          resources: {}
          imagePullPolicy: Always
        restartPolicy: Always
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: qrw-web-service
    name: qrw-web-service
  spec:
    type: NodePort
    selector:
      service: qrw-web-service
    ports:
      - name: '6380'
        port: 6380
kind: List
metadata: {}